
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poke_pocket
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
  
  backend:
    build: ./Backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://db:5432/poke_pocket
      SECRET_KEY: ======================CodeCool=Spring===========================
      EXPIRATION: 6800000

  frontend:
    build: ./Frontend/PokePocket
    depends_on:
      [backend]
    ports:
      [5173:80]
